### ISSUE TITLE
新功能开发申请

### ISSUE THREAD

**Issue by suyu610** [Nevermore1213/library-booking#1]
这个图书馆系统可以查座位上的人的姓名，: > 大佬有空搞搞这个功能吧！

**Comment by Nevermore1213** [comment]
哇，那到时候我试试看XD

**Comment by Nevermore1213** [comment]
应该算是初步完成了，大佬看看还有什么改进的不😘

**Comment by suyu610** [comment]
哈哈哈，你加我Q吧，这里收不到消息~   http://www.uuorb.com/s/about

**Comment by suyu610** [comment]
我突然有个奇怪的点子..是不是可以监控预约系统，当有目标用户预约以后，则发消息推送，来场邂逅？
